# Project information
site_name: Roll Call Club
site_description: 'Everything you need to know about Roll Off in Fall Guys'
site_author: 'Alex Lockwood'
site_url: 'https://alexjlockwood.github.io/roll-call-club'
remote_branch: gh-pages
docs_dir: docs

# Repository
repo_name: 'roll-call-club'
repo_url: 'https://github.com/alexjlockwood/roll-call-club'

# Navigation
nav:
  - 'Overview': index.md
  - 'Getting Started':
      - getting-started/memorizing-the-rolls.md
      - getting-started/understanding-roll-speed.md
      - getting-started/avoiding-desync.md
      - getting-started/counting-laps.md
  - 'Rolls':
      - rolls/5-waller.md
      - rolls/closed-open-open-closed.md
      - rolls/easy-4.md
      - rolls/grand-canyon.md
      - rolls/isolated-duo.md
      - rolls/pillar-trench.md
  - 'Variations':
      - variations/5-waller-grand-canyon.md
      - variations/5-waller-open-closed.md
      - variations/closed-open-grand-canyon.md
      - variations/closed-open-open-closed.md
  - glossary.md

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'deep orange'
    accent: 'blue'
  font:
    text: 'IBM Plex Sans'
    code: 'IBM Plex Mono'

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/alexjlockwood

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - scripts/tablesort.js
